// packages/vue/src/components/ui/HorizontalRuler.vue
<!--
  Mirrors packages/react/src/components/ui/HorizontalRuler.tsx 1:1.
  Same constants, same eighth-inch tick generation (heights 10/6/4/2 px),
  same CSS-triangle indent handles, same margin-zone backgrounds.
-->
<template>
  <div
    ref="rulerRef"
    class="docx-horizontal-ruler"
    :style="containerStyle"
    role="slider"
    aria-label="Horizontal ruler"
    :aria-valuemin="0"
    :aria-valuemax="pageWidthTwips"
  >
    <!-- Margin zones (drag to adjust margin) -->
    <div
      class="docx-horizontal-ruler__margin"
      :style="leftMarginStyle"
      @mousedown.prevent.stop="editable ? startDrag('leftMargin', $event) : null"
    />
    <div
      class="docx-horizontal-ruler__margin"
      :style="rightMarginStyle"
      @mousedown.prevent.stop="editable ? startDrag('rightMargin', $event) : null"
    />

    <!-- Tick marks -->
    <div class="docx-horizontal-ruler__ticks">
      <template v-for="(tick, i) in ticks" :key="i">
        <div
          class="docx-horizontal-ruler__tick-line"
          :style="{ left: tick.position + 'px', height: tick.height + 'px' }"
        />
        <div
          v-if="tick.label"
          class="docx-horizontal-ruler__tick-label"
          :style="{ left: tick.position + 'px' }"
        >
          {{ tick.label }}
        </div>
      </template>
    </div>

    <!-- Table column boundaries: Word-style gray handles shown while inside a table -->
    <div
      v-for="(boundary, i) in tableBoundaries ?? []"
      :key="`${boundary.tablePmStart}-${boundary.kind}-${boundary.columnIndex}-${i}`"
      class="docx-ruler-table-boundary"
      :style="tableBoundaryStyle(boundary, i)"
      role="slider"
      :aria-label="t('ruler.tableColumnBoundary')"
      aria-orientation="horizontal"
      :tabindex="editable ? 0 : -1"
      @mousedown.prevent.stop="startTableBoundaryDrag(boundary, $event)"
      @mouseenter="hoveredTableBoundary = i"
      @mouseleave="hoveredTableBoundary = null"
    >
      <div class="docx-ruler-table-boundary__line" />
    </div>

    <!-- First-line indent: ▼ down at top -->
    <div
      v-if="showFirstLineIndent"
      class="docx-ruler-indent"
      :style="indentContainerStyle('down', firstLinePosPx, dragging === 'firstLineIndent')"
      role="slider"
      :aria-label="t('ruler.firstLineIndent')"
      aria-orientation="horizontal"
      :tabindex="editable ? 0 : -1"
      @mousedown.prevent.stop="editable ? startDrag('firstLineIndent', $event) : null"
      @mouseenter="hovered = 'firstLineIndent'"
      @mouseleave="hovered = null"
    >
      <div :style="triangleStyle('down', triColor('firstLineIndent'))" />
    </div>

    <!-- Left indent: ▲ up at bottom -->
    <div
      v-if="editable"
      class="docx-ruler-indent"
      :style="indentContainerStyle('up', leftIndentPosPx, dragging === 'leftIndent')"
      role="slider"
      :aria-label="t('ruler.leftIndent')"
      aria-orientation="horizontal"
      :tabindex="editable ? 0 : -1"
      @mousedown.prevent.stop="startDrag('leftIndent', $event)"
      @mouseenter="hovered = 'leftIndent'"
      @mouseleave="hovered = null"
    >
      <div :style="triangleStyle('up', triColor('leftIndent'))" />
    </div>

    <!-- Right indent: ▲ up at bottom -->
    <div
      v-if="editable"
      class="docx-ruler-indent"
      :style="indentContainerStyle('up', rightIndentPosPx, dragging === 'rightIndent')"
      role="slider"
      :aria-label="t('ruler.rightIndent')"
      aria-orientation="horizontal"
      :tabindex="editable ? 0 : -1"
      @mousedown.prevent.stop="startDrag('rightIndent', $event)"
      @mouseenter="hovered = 'rightIndent'"
      @mouseleave="hovered = null"
    >
      <div :style="triangleStyle('up', triColor('rightIndent'))" />
    </div>

    <!-- Tab stops -->
    <div
      v-for="(tab, i) in tabStopPositions"
      :key="i"
      class="docx-horizontal-ruler__tab"
      :style="{ left: tab.px + 'px' }"
      :title="`${tab.label}`"
      @dblclick.prevent="$emit('tab-stop-remove', tab.twips)"
    >
      L
    </div>

    <!-- Drag tooltip -->
    <div
      v-if="dragging && tooltipText"
      class="docx-horizontal-ruler__tooltip"
      :style="{ left: tooltipX + 'px' }"
    >
      {{ tooltipText }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onBeforeUnmount, type CSSProperties } from 'vue';
import type { TableRulerCellArea } from '@eigenpal/docx-editor-core/layout-bridge';
import type { TableRulerBoundary } from '@eigenpal/docx-editor-core/prosemirror/tableResize';
import type { SectionProperties, TabStop } from '@eigenpal/docx-editor-core/types/document';
import { twipsToPixels, pixelsToTwips } from '@eigenpal/docx-editor-core/utils/units';
import { useTranslation } from '../../i18n';

type MarkerType =
  | 'leftMargin'
  | 'rightMargin'
  | 'firstLineIndent'
  | 'leftIndent'
  | 'rightIndent'
  | 'tableBoundary';

const props = withDefaults(
  defineProps<{
    sectionProps?: SectionProperties | null;
    zoom?: number;
    editable?: boolean;
    showFirstLineIndent?: boolean;
    firstLineIndent?: number;
    hangingIndent?: boolean;
    indentLeft?: number;
    indentRight?: number;
    unit?: 'inch' | 'cm';
    tabStops?: TabStop[] | null;
    indentArea?: TableRulerCellArea | null;
    tableBoundaries?: TableRulerBoundary[] | null;
  }>(),
  {
    zoom: 1,
    editable: true,
    showFirstLineIndent: true,
    firstLineIndent: 0,
    hangingIndent: false,
    indentLeft: 0,
    indentRight: 0,
    unit: 'inch',
  }
);

const emit = defineEmits<{
  (e: 'left-margin-change', twips: number): void;
  (e: 'right-margin-change', twips: number): void;
  (e: 'first-line-indent-change', twips: number): void;
  (e: 'indent-left-change', twips: number): void;
  (e: 'indent-right-change', twips: number): void;
  (e: 'tab-stop-remove', twips: number): void;
  (e: 'table-boundary-change', boundary: TableRulerBoundary, twips: number): void;
}>();

const { t } = useTranslation();

// Mirror React HorizontalRuler.tsx:50-63
const DEFAULT_PAGE_WIDTH_TWIPS = 12240;
const DEFAULT_MARGIN_TWIPS = 1440;
const TWIPS_PER_INCH = 1440;
const TWIPS_PER_CM = 567;
const RULER_HEIGHT = 22;
const INDENT_COLOR = '#4285f4';
const INDENT_HOVER_COLOR = '#3367d6';
const INDENT_ACTIVE_COLOR = '#2a56c6';
const TABLE_MARKER_COLOR = '#f1f3f4';
const TABLE_MARKER_BORDER = '#b9c0c8';
const TABLE_MARKER_ACTIVE = '#e3e8ef';
const TRI_SIZE = 5;
const TRI_HEIGHT = Math.round(TRI_SIZE * 1.6); // 8

const rulerRef = ref<HTMLElement | null>(null);
const dragging = ref<MarkerType | null>(null);
const hovered = ref<MarkerType | null>(null);
const hoveredTableBoundary = ref<number | null>(null);
const activeTableBoundary = ref<TableRulerBoundary | null>(null);
const tooltipX = ref(0);
const tooltipText = ref('');

// Wrappers around core's twipsToPixels/pixelsToTwips that fold in the
// current zoom factor (core helpers are zoom-agnostic).
function tw2px(twips: number): number {
  return twipsToPixels(twips) * props.zoom;
}
function px2tw(px: number): number {
  return Math.round(pixelsToTwips(px / props.zoom));
}

const pageWidthTwips = computed(() => props.sectionProps?.pageWidth ?? DEFAULT_PAGE_WIDTH_TWIPS);
const leftMarginTwips = computed(() => props.sectionProps?.marginLeft ?? DEFAULT_MARGIN_TWIPS);
const rightMarginTwips = computed(() => props.sectionProps?.marginRight ?? DEFAULT_MARGIN_TWIPS);
const indentAreaLeftTwips = computed(() => props.indentArea?.leftTwips ?? leftMarginTwips.value);
const indentAreaRightTwips = computed(
  () => props.indentArea?.rightTwips ?? pageWidthTwips.value - rightMarginTwips.value
);
const indentAreaWidthTwips = computed(() =>
  Math.max(0, indentAreaRightTwips.value - indentAreaLeftTwips.value)
);

const pageWidthPx = computed(() => tw2px(pageWidthTwips.value));
const leftMarginPx = computed(() => tw2px(leftMarginTwips.value));
const rightMarginPx = computed(() => tw2px(rightMarginTwips.value));
const indentAreaLeftPx = computed(() => tw2px(indentAreaLeftTwips.value));
const indentAreaRightPx = computed(() => tw2px(indentAreaRightTwips.value));
const indentLeftPx = computed(() => tw2px(props.indentLeft));
const indentRightPx = computed(() => tw2px(props.indentRight));
const effectiveFirstLine = computed(() =>
  props.hangingIndent ? -Math.abs(props.firstLineIndent) : props.firstLineIndent
);
const firstLineIndentPx = computed(() => tw2px(effectiveFirstLine.value));

const leftIndentPosPx = computed(() => indentAreaLeftPx.value + indentLeftPx.value);
const rightIndentPosPx = computed(() => indentAreaRightPx.value - indentRightPx.value);
const firstLinePosPx = computed(
  () => indentAreaLeftPx.value + indentLeftPx.value + firstLineIndentPx.value
);

const containerStyle = computed<CSSProperties>(() => ({
  position: 'relative',
  width: pageWidthPx.value + 'px',
  height: RULER_HEIGHT + 'px',
  backgroundColor: 'transparent',
  overflow: 'visible',
  userSelect: 'none',
  cursor: dragging.value ? 'ew-resize' : 'default',
}));

const leftMarginStyle = computed<CSSProperties>(() => ({
  position: 'absolute',
  top: 0,
  left: 0,
  width: leftMarginPx.value + 'px',
  height: RULER_HEIGHT + 'px',
  backgroundColor: 'rgba(0, 0, 0, 0.02)',
  borderRight: '1px solid rgba(0,0,0,0.06)',
  cursor: props.editable ? 'ew-resize' : 'default',
  zIndex: 1,
}));
const rightMarginStyle = computed<CSSProperties>(() => ({
  position: 'absolute',
  top: 0,
  right: 0,
  width: rightMarginPx.value + 'px',
  height: RULER_HEIGHT + 'px',
  backgroundColor: 'rgba(0, 0, 0, 0.02)',
  borderLeft: '1px solid rgba(0,0,0,0.06)',
  cursor: props.editable ? 'ew-resize' : 'default',
  zIndex: 1,
}));

// Mirror generateTicks() in React HorizontalRuler.tsx:549.
// Eighth-inch ticks; major every inch (height 10), quarters height 6,
// halves height 4, eighths height 2.
const ticks = computed(() => {
  const out: { position: number; height: number; label?: string }[] = [];
  if (props.unit === 'inch') {
    const eighth = TWIPS_PER_INCH / 8;
    const total = Math.ceil(pageWidthTwips.value / eighth);
    for (let i = 0; i <= total; i++) {
      const twPos = i * eighth;
      if (twPos > pageWidthTwips.value) break;
      const px = tw2px(twPos);
      if (i % 8 === 0) {
        out.push({ position: px, height: 10, label: i / 8 > 0 ? String(i / 8) : undefined });
      } else if (i % 4 === 0) {
        out.push({ position: px, height: 6 });
      } else if (i % 2 === 0) {
        out.push({ position: px, height: 4 });
      } else {
        out.push({ position: px, height: 2 });
      }
    }
  } else {
    const mm = TWIPS_PER_CM / 10;
    const total = Math.ceil(pageWidthTwips.value / mm);
    for (let i = 0; i <= total; i++) {
      const twPos = i * mm;
      if (twPos > pageWidthTwips.value) break;
      const px = tw2px(twPos);
      if (i % 10 === 0) {
        out.push({ position: px, height: 10, label: i / 10 > 0 ? String(i / 10) : undefined });
      } else if (i % 5 === 0) {
        out.push({ position: px, height: 6 });
      } else {
        out.push({ position: px, height: 3 });
      }
    }
  }
  return out;
});

const tabStopPositions = computed(() => {
  if (!props.tabStops?.length) return [];
  return props.tabStops.map((ts) => {
    const pos = (ts as any).position ?? ts.pos ?? 0;
    return { px: tw2px(pos), twips: pos, label: formatValue(pos) };
  });
});

function formatValue(twips: number): string {
  if (props.unit === 'cm') return (twips / TWIPS_PER_CM).toFixed(1) + ' cm';
  return (twips / TWIPS_PER_INCH).toFixed(2) + '"';
}

function clampRounded(value: number, min: number, max: number): number {
  return Math.round(Math.max(min, Math.min(value, max)));
}

function triColor(marker: MarkerType): string {
  if (dragging.value === marker) return INDENT_ACTIVE_COLOR;
  if (hovered.value === marker) return INDENT_HOVER_COLOR;
  return INDENT_COLOR;
}

function indentContainerStyle(
  direction: 'up' | 'down',
  positionPx: number,
  isDragging: boolean
): CSSProperties {
  return {
    position: 'absolute',
    left: positionPx - TRI_SIZE + 'px',
    width: TRI_SIZE * 2 + 'px',
    height: TRI_HEIGHT + 2 + 'px',
    cursor: props.editable ? 'ew-resize' : 'default',
    zIndex: isDragging ? 10 : 4,
    ...(direction === 'down' ? { top: 0 } : { bottom: 0 }),
  };
}

function triangleStyle(direction: 'up' | 'down', color: string): CSSProperties {
  if (direction === 'down') {
    return {
      position: 'absolute',
      top: '1px',
      left: 0,
      width: 0,
      height: 0,
      borderLeft: `${TRI_SIZE}px solid transparent`,
      borderRight: `${TRI_SIZE}px solid transparent`,
      borderTop: `${TRI_HEIGHT}px solid ${color}`,
      transition: 'border-top-color 0.1s',
    };
  }
  return {
    position: 'absolute',
    bottom: '1px',
    left: 0,
    width: 0,
    height: 0,
    borderLeft: `${TRI_SIZE}px solid transparent`,
    borderRight: `${TRI_SIZE}px solid transparent`,
    borderBottom: `${TRI_HEIGHT}px solid ${color}`,
    transition: 'border-bottom-color 0.1s',
  };
}

function sameBoundary(a: TableRulerBoundary | null, b: TableRulerBoundary): boolean {
  return (
    !!a && a.tablePmStart === b.tablePmStart && a.columnIndex === b.columnIndex && a.kind === b.kind
  );
}

function tableBoundaryStyle(boundary: TableRulerBoundary, index: number): CSSProperties {
  const isDragging =
    dragging.value === 'tableBoundary' && sameBoundary(activeTableBoundary.value, boundary);
  const isHovered = hoveredTableBoundary.value === index;
  return {
    position: 'absolute',
    left: tw2px(boundary.positionTwips) - 8 + 'px',
    top: '1px',
    width: '16px',
    height: RULER_HEIGHT - 3 + 'px',
    border: `1px solid ${TABLE_MARKER_BORDER}`,
    backgroundColor: isDragging || isHovered ? TABLE_MARKER_ACTIVE : TABLE_MARKER_COLOR,
    boxSizing: 'border-box',
    cursor: props.editable ? 'col-resize' : 'default',
    zIndex: isDragging ? 11 : 5,
  };
}

function initialDragValue(type: MarkerType): number {
  if (type === 'leftMargin') return leftMarginTwips.value;
  if (type === 'rightMargin') return rightMarginTwips.value;
  if (type === 'leftIndent') return props.indentLeft;
  if (type === 'rightIndent') return props.indentRight;
  if (type === 'firstLineIndent') return props.firstLineIndent;
  return activeTableBoundary.value?.positionTwips ?? 0;
}

function beginDrag(event: MouseEvent, initialValue: number) {
  tooltipX.value = event.clientX - (rulerRef.value?.getBoundingClientRect().left ?? 0);
  tooltipText.value = formatValue(initialValue);

  document.addEventListener('mousemove', handleMove);
  document.addEventListener('mouseup', handleUp);
}

function startDrag(type: MarkerType, event: MouseEvent) {
  if (!props.editable) return;
  dragging.value = type;
  beginDrag(event, initialDragValue(type));
}

function startTableBoundaryDrag(boundary: TableRulerBoundary, event: MouseEvent) {
  if (!props.editable) return;
  dragging.value = 'tableBoundary';
  activeTableBoundary.value = boundary;
  beginDrag(event, boundary.positionTwips);
}

function handleMove(e: MouseEvent) {
  if (!dragging.value || !rulerRef.value) return;
  const rect = rulerRef.value.getBoundingClientRect();
  if (!rect) return;
  const x = e.clientX - rect.left;
  const positionTwips = px2tw(x);
  const value = computeNewValue(dragging.value, positionTwips);
  tooltipX.value = dragging.value === 'tableBoundary' ? tw2px(value) : x;
  tooltipText.value = formatValue(value);
  emitChange(dragging.value, value);
}

function handleUp(_e: MouseEvent) {
  dragging.value = null;
  activeTableBoundary.value = null;
  document.removeEventListener('mousemove', handleMove);
  document.removeEventListener('mouseup', handleUp);
}

function computeNewValue(marker: MarkerType, positionTwips: number): number {
  if (marker === 'tableBoundary') {
    const boundary = activeTableBoundary.value;
    if (!boundary) return Math.round(positionTwips);
    return clampRounded(positionTwips, boundary.minTwips, boundary.maxTwips);
  }
  if (marker === 'leftMargin') {
    const max = pageWidthTwips.value - rightMarginTwips.value - 720;
    return clampRounded(positionTwips, 0, max);
  }
  if (marker === 'rightMargin') {
    const fromRight = pageWidthTwips.value - positionTwips;
    const max = pageWidthTwips.value - leftMarginTwips.value - 720;
    return clampRounded(fromRight, 0, max);
  }
  if (marker === 'firstLineIndent') {
    const base = indentAreaLeftTwips.value + props.indentLeft;
    const indentFromBase = positionTwips - base;
    const max = Math.max(
      -props.indentLeft,
      indentAreaWidthTwips.value - props.indentLeft - props.indentRight - 720
    );
    return clampRounded(indentFromBase, -props.indentLeft, max);
  }
  if (marker === 'leftIndent') {
    const indentFromMargin = positionTwips - indentAreaLeftTwips.value;
    const max = Math.max(0, indentAreaWidthTwips.value - props.indentRight - 720);
    return clampRounded(indentFromMargin, 0, max);
  }
  // rightIndent
  const rightEdge = indentAreaRightTwips.value;
  const indentFromRight = rightEdge - positionTwips;
  const max = Math.max(0, indentAreaWidthTwips.value - props.indentLeft - 720);
  return clampRounded(indentFromRight, 0, max);
}

function emitChange(marker: MarkerType, value: number) {
  switch (marker) {
    case 'leftMargin':
      emit('left-margin-change', value);
      break;
    case 'rightMargin':
      emit('right-margin-change', value);
      break;
    case 'firstLineIndent':
      emit('first-line-indent-change', value);
      break;
    case 'leftIndent':
      emit('indent-left-change', value);
      break;
    case 'rightIndent':
      emit('indent-right-change', value);
      break;
    case 'tableBoundary':
      if (activeTableBoundary.value) {
        emit('table-boundary-change', activeTableBoundary.value, value);
      }
      break;
  }
}

onBeforeUnmount(() => {
  document.removeEventListener('mousemove', handleMove);
  document.removeEventListener('mouseup', handleUp);
});
</script>

<style scoped>
.docx-horizontal-ruler {
  display: block;
  position: relative;
  flex-shrink: 0;
}
.docx-horizontal-ruler__ticks {
  position: absolute;
  inset: 0;
  pointer-events: none;
}
/* Mirror React RulerTick: line at bottom, 1px wide, color via CSS var
   (--doc-text-subtle); falls back to #9aa0a6 if --doc-text-subtle is unset
   in the consumer scope. */
.docx-horizontal-ruler__tick-line {
  position: absolute;
  bottom: 0;
  width: 1px;
  background-color: var(--doc-text-subtle, #9aa0a6);
}
.docx-horizontal-ruler__tick-label {
  position: absolute;
  top: 3px;
  transform: translateX(-50%);
  font-size: 9px;
  color: var(--doc-text-muted, #5f6368);
  font-family: sans-serif;
  white-space: nowrap;
}
.docx-horizontal-ruler__tab {
  position: absolute;
  bottom: 0;
  width: 10px;
  height: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 8px;
  font-weight: 700;
  color: #555;
  cursor: pointer;
  user-select: none;
  transform: translateX(-5px);
}
.docx-ruler-table-boundary {
  user-select: none;
}
.docx-ruler-table-boundary__line {
  position: absolute;
  left: 50%;
  top: 2px;
  bottom: 2px;
  border-left: 1px dotted #b9c0c8;
}
.docx-horizontal-ruler__tooltip {
  position: absolute;
  top: -22px;
  transform: translateX(-50%);
  background: #333;
  color: #fff;
  font-size: 10px;
  font-family: sans-serif;
  padding: 2px 6px;
  border-radius: 3px;
  white-space: nowrap;
  pointer-events: none;
  z-index: 20;
}
</style>

// packages/react/src/components/ui/HorizontalRuler.tsx
/**
 * HorizontalRuler Component — Google Docs style
 *
 * 3 handles only:
 * - Left side: first-line indent (▼ down at top) + left indent (▲ up at bottom)
 * - Right side: right indent (▲ up at bottom)
 *
 * Margins shown as gray zones on the ruler edges.
 * Drag the boundary between gray/white to adjust page margins.
 * Drag tooltip shows value during any drag.
 */

import React, { useState, useRef, useCallback, useEffect } from 'react';
import type { CSSProperties } from 'react';
import type { TableRulerCellArea } from '@eigenpal/docx-editor-core/layout-bridge';
import type { TableRulerBoundary } from '@eigenpal/docx-editor-core/prosemirror/tableResize';
import type { SectionProperties, TabStop } from '@eigenpal/docx-editor-core/types/document';
import { twipsToPixels, pixelsToTwips, formatPx } from '@eigenpal/docx-editor-core/utils';
import { useTranslation } from '../../i18n';

// ============================================================================
// TYPES
// ============================================================================

export interface HorizontalRulerProps {
  sectionProps?: SectionProperties | null;
  zoom?: number;
  editable?: boolean;
  onLeftMarginChange?: (marginTwips: number) => void;
  onRightMarginChange?: (marginTwips: number) => void;
  onFirstLineIndentChange?: (indentTwips: number) => void;
  showFirstLineIndent?: boolean;
  firstLineIndent?: number;
  hangingIndent?: boolean;
  indentLeft?: number;
  indentRight?: number;
  onIndentLeftChange?: (indentTwips: number) => void;
  onIndentRightChange?: (indentTwips: number) => void;
  unit?: 'inch' | 'cm';
  className?: string;
  style?: CSSProperties;
  tabStops?: TabStop[] | null;
  onTabStopRemove?: (positionTwips: number) => void;
  indentArea?: TableRulerCellArea | null;
  tableBoundaries?: TableRulerBoundary[] | null;
  onTableBoundaryChange?: (boundary: TableRulerBoundary, positionTwips: number) => void;
}

type MarkerType =
  | 'leftMargin'
  | 'rightMargin'
  | 'firstLineIndent'
  | 'leftIndent'
  | 'rightIndent'
  | 'tableBoundary';

// ============================================================================
// CONSTANTS
// ============================================================================

const DEFAULT_PAGE_WIDTH_TWIPS = 12240;
const DEFAULT_MARGIN_TWIPS = 1440;
const TWIPS_PER_INCH = 1440;
const TWIPS_PER_CM = 567;

const RULER_HEIGHT = 22;
const RULER_TEXT_COLOR = 'var(--doc-text-muted)';
const RULER_TICK_COLOR = 'var(--doc-text-subtle)';
const MARGIN_ZONE_COLOR = 'rgba(0, 0, 0, 0.02)';
const INDENT_COLOR = '#4285f4';
const INDENT_HOVER_COLOR = '#3367d6';
const INDENT_ACTIVE_COLOR = '#2a56c6';
const TABLE_MARKER_COLOR = '#f1f3f4';
const TABLE_MARKER_BORDER = '#b9c0c8';
const TABLE_MARKER_ACTIVE = '#e3e8ef';

const TRI_SIZE = 5; // triangle half-width in px

// ============================================================================
// HELPERS
// ============================================================================

function formatValueForTooltip(twips: number, unit: 'inch' | 'cm'): string {
  if (unit === 'inch') {
    return (twips / TWIPS_PER_INCH).toFixed(2) + '"';
  }
  return (twips / TWIPS_PER_CM).toFixed(1) + ' cm';
}

function sameTableBoundary(a: TableRulerBoundary | null, b: TableRulerBoundary): boolean {
  return (
    !!a && a.tablePmStart === b.tablePmStart && a.columnIndex === b.columnIndex && a.kind === b.kind
  );
}

function clampRounded(value: number, min: number, max: number): number {
  return Math.round(Math.max(min, Math.min(value, max)));
}

// ============================================================================
// MAIN COMPONENT
// ============================================================================

export function HorizontalRuler({
  sectionProps,
  zoom = 1,
  editable = false,
  onLeftMarginChange,
  onRightMarginChange,
  onFirstLineIndentChange,
  showFirstLineIndent = true,
  firstLineIndent = 0,
  hangingIndent = false,
  indentLeft = 0,
  indentRight = 0,
  onIndentLeftChange,
  onIndentRightChange,
  unit = 'inch',
  className = '',
  style,
  tabStops,
  onTabStopRemove,
  indentArea,
  tableBoundaries,
  onTableBoundaryChange,
}: HorizontalRulerProps): React.ReactElement {
  const { t } = useTranslation();
  const [dragging, setDragging] = useState<MarkerType | null>(null);
  const [hoveredMarker, setHoveredMarker] = useState<MarkerType | null>(null);
  const [hoveredTableBoundary, setHoveredTableBoundary] = useState<number | null>(null);
  const [dragValue, setDragValue] = useState<number | null>(null);
  const [dragPositionPx, setDragPositionPx] = useState<number | null>(null);
  const rulerRef = useRef<HTMLDivElement>(null);
  const activeTableBoundaryRef = useRef<TableRulerBoundary | null>(null);

  // Page dimensions
  const pageWidthTwips = sectionProps?.pageWidth ?? DEFAULT_PAGE_WIDTH_TWIPS;
  const leftMarginTwips = sectionProps?.marginLeft ?? DEFAULT_MARGIN_TWIPS;
  const rightMarginTwips = sectionProps?.marginRight ?? DEFAULT_MARGIN_TWIPS;
  const indentAreaLeftTwips = indentArea?.leftTwips ?? leftMarginTwips;
  const indentAreaRightTwips = indentArea?.rightTwips ?? pageWidthTwips - rightMarginTwips;
  const indentAreaWidthTwips = Math.max(0, indentAreaRightTwips - indentAreaLeftTwips);

  // Pixel conversions
  const pageWidthPx = twipsToPixels(pageWidthTwips) * zoom;
  const leftMarginPx = twipsToPixels(leftMarginTwips) * zoom;
  const rightMarginPx = twipsToPixels(rightMarginTwips) * zoom;
  const indentAreaLeftPx = twipsToPixels(indentAreaLeftTwips) * zoom;
  const indentAreaRightPx = twipsToPixels(indentAreaRightTwips) * zoom;
  const indentLeftPx = twipsToPixels(indentLeft) * zoom;
  const indentRightPx = twipsToPixels(indentRight) * zoom;

  // First line indent: hanging goes left, normal goes right
  const effectiveFirstLineIndent = hangingIndent ? -Math.abs(firstLineIndent) : firstLineIndent;
  const firstLineIndentPx = twipsToPixels(effectiveFirstLineIndent) * zoom;

  // Handle positions (in px from ruler left edge)
  const leftIndentPosPx = indentAreaLeftPx + indentLeftPx;
  const rightIndentPosPx = indentAreaRightPx - indentRightPx;
  const firstLinePosPx = indentAreaLeftPx + indentLeftPx + firstLineIndentPx;

  const handleDragStart = useCallback(
    (e: React.MouseEvent, marker: MarkerType) => {
      if (!editable) return;
      e.preventDefault();
      e.stopPropagation();
      setDragging(marker);
    },
    [editable]
  );

  const handleTableBoundaryDragStart = useCallback(
    (e: React.MouseEvent, boundary: TableRulerBoundary) => {
      if (!editable || !onTableBoundaryChange) return;
      e.preventDefault();
      e.stopPropagation();
      activeTableBoundaryRef.current = boundary;
      setDragging('tableBoundary');
    },
    [editable, onTableBoundaryChange]
  );

  const handleDrag = useCallback(
    (e: MouseEvent) => {
      if (!dragging || !rulerRef.current) return;

      const rect = rulerRef.current.getBoundingClientRect();
      const x = e.clientX - rect.left;
      setDragPositionPx(x);
      const positionTwips = pixelsToTwips(x / zoom);

      if (dragging === 'tableBoundary') {
        const boundary = activeTableBoundaryRef.current;
        if (!boundary) return;
        const rounded = clampRounded(positionTwips, boundary.minTwips, boundary.maxTwips);
        setDragValue(rounded);
        setDragPositionPx(twipsToPixels(rounded) * zoom);
        onTableBoundaryChange?.(boundary, rounded);
      } else if (dragging === 'leftMargin') {
        const maxMargin = pageWidthTwips - rightMarginTwips - 720;
        const rounded = clampRounded(positionTwips, 0, maxMargin);
        setDragValue(rounded);
        onLeftMarginChange?.(rounded);
      } else if (dragging === 'rightMargin') {
        const fromRight = pageWidthTwips - positionTwips;
        const maxMargin = pageWidthTwips - leftMarginTwips - 720;
        const rounded = clampRounded(fromRight, 0, maxMargin);
        setDragValue(rounded);
        onRightMarginChange?.(rounded);
      } else if (dragging === 'firstLineIndent') {
        const base = indentAreaLeftTwips + indentLeft;
        const indentFromBase = positionTwips - base;
        const maxIndent = Math.max(
          -indentLeft,
          indentAreaWidthTwips - indentLeft - indentRight - 720
        );
        const rounded = clampRounded(indentFromBase, -indentLeft, maxIndent);
        setDragValue(rounded);
        onFirstLineIndentChange?.(rounded);
      } else if (dragging === 'leftIndent') {
        const indentFromMargin = positionTwips - indentAreaLeftTwips;
        const maxIndent = Math.max(0, indentAreaWidthTwips - indentRight - 720);
        const rounded = clampRounded(indentFromMargin, 0, maxIndent);
        setDragValue(rounded);
        onIndentLeftChange?.(rounded);
      } else if (dragging === 'rightIndent') {
        const rightEdge = indentAreaRightTwips;
        const indentFromRight = rightEdge - positionTwips;
        const maxIndent = Math.max(0, indentAreaWidthTwips - indentLeft - 720);
        const rounded = clampRounded(indentFromRight, 0, maxIndent);
        setDragValue(rounded);
        onIndentRightChange?.(rounded);
      }
    },
    [
      dragging,
      zoom,
      pageWidthTwips,
      leftMarginTwips,
      rightMarginTwips,
      indentAreaLeftTwips,
      indentAreaRightTwips,
      indentAreaWidthTwips,
      indentLeft,
      indentRight,
      onLeftMarginChange,
      onRightMarginChange,
      onFirstLineIndentChange,
      onIndentLeftChange,
      onIndentRightChange,
      onTableBoundaryChange,
    ]
  );

  const handleDragEnd = useCallback(() => {
    setDragging(null);
    setDragValue(null);
    setDragPositionPx(null);
    activeTableBoundaryRef.current = null;
  }, []);

  useEffect(() => {
    if (dragging) {
      document.addEventListener('mousemove', handleDrag);
      document.addEventListener('mouseup', handleDragEnd);
      return () => {
        document.removeEventListener('mousemove', handleDrag);
        document.removeEventListener('mouseup', handleDragEnd);
      };
    }
  }, [dragging, handleDrag, handleDragEnd]);

  const ticks = generateTicks(pageWidthTwips, zoom, unit);

  return (
    <div
      ref={rulerRef}
      className={`docx-horizontal-ruler ${className}`}
      style={{
        position: 'relative',
        width: formatPx(pageWidthPx),
        height: RULER_HEIGHT,
        backgroundColor: 'transparent',
        overflow: 'visible',
        userSelect: 'none',
        cursor: dragging ? 'ew-resize' : 'default',
        ...style,
      }}
      role="slider"
      aria-label={t('ruler.horizontal')}
      aria-valuemin={0}
      aria-valuemax={pageWidthTwips}
    >
      {/* Gray margin zones — click & drag anywhere in the gray area to adjust margin */}
      <div
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          width: formatPx(leftMarginPx),
          height: RULER_HEIGHT,
          backgroundColor: MARGIN_ZONE_COLOR,
          borderRight: '1px solid rgba(0,0,0,0.06)',
          cursor: editable ? 'ew-resize' : 'default',
          zIndex: 1,
        }}
        onMouseDown={
          editable && onLeftMarginChange ? (e) => handleDragStart(e, 'leftMargin') : undefined
        }
      />
      <div
        style={{
          position: 'absolute',
          top: 0,
          right: 0,
          width: formatPx(rightMarginPx),
          height: RULER_HEIGHT,
          backgroundColor: MARGIN_ZONE_COLOR,
          borderLeft: '1px solid rgba(0,0,0,0.06)',
          cursor: editable ? 'ew-resize' : 'default',
          zIndex: 1,
        }}
        onMouseDown={
          editable && onRightMarginChange ? (e) => handleDragStart(e, 'rightMargin') : undefined
        }
      />

      {/* Tick marks */}
      <div style={{ position: 'absolute', inset: 0, pointerEvents: 'none' }}>
        {ticks.map((tick, i) => (
          <RulerTick key={i} tick={tick} />
        ))}
      </div>

      {/* === 3 INDENT HANDLES (Google Docs style) === */}

      {/* Table column boundaries — Word-style gray handles shown while inside a table */}
      {tableBoundaries?.map((boundary, index) => (
        <TableBoundaryMarker
          key={`${boundary.tablePmStart}-${boundary.kind}-${boundary.columnIndex}-${index}`}
          positionPx={twipsToPixels(boundary.positionTwips) * zoom}
          editable={editable && !!onTableBoundaryChange}
          isDragging={
            dragging === 'tableBoundary' &&
            sameTableBoundary(activeTableBoundaryRef.current, boundary)
          }
          isHovered={hoveredTableBoundary === index}
          onMouseEnter={() => setHoveredTableBoundary(index)}
          onMouseLeave={() => setHoveredTableBoundary(null)}
          onMouseDown={(e) => handleTableBoundaryDragStart(e, boundary)}
          label={t('ruler.tableColumnBoundary')}
        />
      ))}

      {/* First-line indent — ▼ down triangle at top-left */}
      {showFirstLineIndent && (
        <IndentTriangle
          direction="down"
          positionPx={firstLinePosPx}
          editable={editable}
          isDragging={dragging === 'firstLineIndent'}
          isHovered={hoveredMarker === 'firstLineIndent'}
          onMouseEnter={() => setHoveredMarker('firstLineIndent')}
          onMouseLeave={() => setHoveredMarker(null)}
          onMouseDown={(e) => handleDragStart(e, 'firstLineIndent')}
          label={t('ruler.firstLineIndent')}
        />
      )}

      {/* Left indent — ▲ up triangle at bottom-left */}
      {editable && onIndentLeftChange && (
        <IndentTriangle
          direction="up"
          positionPx={leftIndentPosPx}
          editable={editable}
          isDragging={dragging === 'leftIndent'}
          isHovered={hoveredMarker === 'leftIndent'}
          onMouseEnter={() => setHoveredMarker('leftIndent')}
          onMouseLeave={() => setHoveredMarker(null)}
          onMouseDown={(e) => handleDragStart(e, 'leftIndent')}
          label={t('ruler.leftIndent')}
        />
      )}

      {/* Right indent — ▲ up triangle at bottom-right */}
      {editable && onIndentRightChange && (
        <IndentTriangle
          direction="up"
          positionPx={rightIndentPosPx}
          editable={editable}
          isDragging={dragging === 'rightIndent'}
          isHovered={hoveredMarker === 'rightIndent'}
          onMouseEnter={() => setHoveredMarker('rightIndent')}
          onMouseLeave={() => setHoveredMarker(null)}
          onMouseDown={(e) => handleDragStart(e, 'rightIndent')}
          label={t('ruler.rightIndent')}
        />
      )}

      {/* Tab stop markers (display only) */}
      {tabStops?.map((tab) => (
        <TabStopMarker
          key={tab.position}
          tabStop={tab}
          positionPx={twipsToPixels(tab.position) * zoom}
          onDoubleClick={() => onTabStopRemove?.(tab.position)}
        />
      ))}

      {/* Drag tooltip */}
      {dragging && dragValue !== null && dragPositionPx !== null && (
        <DragTooltip value={formatValueForTooltip(dragValue, unit)} positionPx={dragPositionPx} />
      )}
    </div>
  );
}

// ============================================================================
// SUB-COMPONENTS
// ============================================================================

interface TickData {
  position: number;
  height: number;
  label?: string;
}

function RulerTick({ tick }: { tick: TickData }): React.ReactElement {
  return (
    <>
      <div
        style={{
          position: 'absolute',
          left: formatPx(tick.position),
          bottom: 0,
          width: 1,
          height: tick.height,
          backgroundColor: RULER_TICK_COLOR,
        }}
      />
      {tick.label && (
        <div
          style={{
            position: 'absolute',
            left: formatPx(tick.position),
            top: 3,
            transform: 'translateX(-50%)',
            fontSize: '9px',
            color: RULER_TEXT_COLOR,
            fontFamily: 'sans-serif',
            whiteSpace: 'nowrap',
          }}
        >
          {tick.label}
        </div>
      )}
    </>
  );
}

/**
 * Indent triangle handle — Google Docs style.
 * direction="down": ▼ anchored at top (first-line indent)
 * direction="up":   ▲ anchored at bottom (left/right paragraph indents)
 */
interface IndentTriangleProps {
  direction: 'up' | 'down';
  positionPx: number;
  editable: boolean;
  isDragging: boolean;
  isHovered: boolean;
  onMouseEnter: () => void;
  onMouseLeave: () => void;
  onMouseDown: (e: React.MouseEvent) => void;
  label: string;
}

function IndentTriangle({
  direction,
  positionPx,
  editable,
  isDragging,
  isHovered,
  onMouseEnter,
  onMouseLeave,
  onMouseDown,
  label,
}: IndentTriangleProps): React.ReactElement {
  const color = isDragging ? INDENT_ACTIVE_COLOR : isHovered ? INDENT_HOVER_COLOR : INDENT_COLOR;
  const triHeight = Math.round(TRI_SIZE * 1.6);

  const containerStyle: CSSProperties = {
    position: 'absolute',
    left: formatPx(positionPx - TRI_SIZE),
    width: TRI_SIZE * 2,
    height: triHeight + 2,
    cursor: editable ? 'ew-resize' : 'default',
    zIndex: isDragging ? 10 : 4,
    ...(direction === 'down' ? { top: 0 } : { bottom: 0 }),
  };

  const triangleStyle: CSSProperties =
    direction === 'down'
      ? {
          position: 'absolute',
          top: 1,
          left: 0,
          width: 0,
          height: 0,
          borderLeft: `${TRI_SIZE}px solid transparent`,
          borderRight: `${TRI_SIZE}px solid transparent`,
          borderTop: `${triHeight}px solid ${color}`,
          transition: 'border-top-color 0.1s',
        }
      : {
          position: 'absolute',
          bottom: 1,
          left: 0,
          width: 0,
          height: 0,
          borderLeft: `${TRI_SIZE}px solid transparent`,
          borderRight: `${TRI_SIZE}px solid transparent`,
          borderBottom: `${triHeight}px solid ${color}`,
          transition: 'border-bottom-color 0.1s',
        };

  return (
    <div
      className="docx-ruler-indent"
      style={containerStyle}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      onMouseDown={onMouseDown}
      role="slider"
      aria-label={label}
      aria-orientation="horizontal"
      tabIndex={editable ? 0 : -1}
    >
      <div style={triangleStyle} />
    </div>
  );
}

interface TableBoundaryMarkerProps {
  positionPx: number;
  editable: boolean;
  isDragging: boolean;
  isHovered: boolean;
  onMouseEnter: () => void;
  onMouseLeave: () => void;
  onMouseDown: (e: React.MouseEvent) => void;
  label: string;
}

function TableBoundaryMarker({
  positionPx,
  editable,
  isDragging,
  isHovered,
  onMouseEnter,
  onMouseLeave,
  onMouseDown,
  label,
}: TableBoundaryMarkerProps): React.ReactElement {
  const bg = isDragging || isHovered ? TABLE_MARKER_ACTIVE : TABLE_MARKER_COLOR;

  return (
    <div
      className="docx-ruler-table-boundary"
      style={{
        position: 'absolute',
        left: formatPx(positionPx - 8),
        top: 1,
        width: 16,
        height: RULER_HEIGHT - 3,
        border: `1px solid ${TABLE_MARKER_BORDER}`,
        backgroundColor: bg,
        boxSizing: 'border-box',
        cursor: editable ? 'col-resize' : 'default',
        zIndex: isDragging ? 11 : 5,
      }}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      onMouseDown={onMouseDown}
      role="slider"
      aria-label={label}
      aria-orientation="horizontal"
      tabIndex={editable ? 0 : -1}
    >
      <div
        style={{
          position: 'absolute',
          left: '50%',
          top: 2,
          bottom: 2,
          borderLeft: `1px dotted ${TABLE_MARKER_BORDER}`,
        }}
      />
    </div>
  );
}

function DragTooltip({
  value,
  positionPx,
}: {
  value: string;
  positionPx: number;
}): React.ReactElement {
  return (
    <div
      style={{
        position: 'absolute',
        left: formatPx(positionPx),
        top: -22,
        transform: 'translateX(-50%)',
        backgroundColor: '#333',
        color: '#fff',
        fontSize: '10px',
        fontFamily: 'sans-serif',
        padding: '2px 6px',
        borderRadius: 3,
        whiteSpace: 'nowrap',
        pointerEvents: 'none',
        zIndex: 20,
      }}
    >
      {value}
    </div>
  );
}

interface TabStopMarkerProps {
  tabStop: TabStop;
  positionPx: number;
  onDoubleClick: () => void;
}

const TAB_SYMBOLS: Record<string, string> = {
  left: 'L',
  center: 'C',
  right: 'R',
  decimal: 'D',
  bar: '|',
};

function TabStopMarker({
  tabStop,
  positionPx,
  onDoubleClick,
}: TabStopMarkerProps): React.ReactElement {
  return (
    <div
      style={{
        position: 'absolute',
        left: formatPx(positionPx - 5),
        bottom: 0,
        width: 10,
        height: 12,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 8,
        fontWeight: 700,
        color: '#555',
        cursor: 'pointer',
        userSelect: 'none',
      }}
      onDoubleClick={(e) => {
        e.stopPropagation();
        onDoubleClick();
      }}
      title={`${tabStop.alignment} tab at ${(tabStop.position / 1440).toFixed(2)}"`}
    >
      {TAB_SYMBOLS[tabStop.alignment] || 'L'}
    </div>
  );
}

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

function generateTicks(pageWidthTwips: number, zoom: number, unit: 'inch' | 'cm'): TickData[] {
  const ticks: TickData[] = [];

  if (unit === 'inch') {
    const eighthInchTwips = TWIPS_PER_INCH / 8;
    const totalEighths = Math.ceil(pageWidthTwips / eighthInchTwips);
    for (let i = 0; i <= totalEighths; i++) {
      const twipsPos = i * eighthInchTwips;
      if (twipsPos > pageWidthTwips) break;
      const pxPos = twipsToPixels(twipsPos) * zoom;
      if (i % 8 === 0) {
        ticks.push({ position: pxPos, height: 10, label: i / 8 > 0 ? String(i / 8) : undefined });
      } else if (i % 4 === 0) {
        ticks.push({ position: pxPos, height: 6 });
      } else if (i % 2 === 0) {
        ticks.push({ position: pxPos, height: 4 });
      } else {
        ticks.push({ position: pxPos, height: 2 });
      }
    }
  } else {
    const mmTwips = TWIPS_PER_CM / 10;
    const totalMm = Math.ceil(pageWidthTwips / mmTwips);
    for (let i = 0; i <= totalMm; i++) {
      const twipsPos = i * mmTwips;
      if (twipsPos > pageWidthTwips) break;
      const pxPos = twipsToPixels(twipsPos) * zoom;
      if (i % 10 === 0) {
        ticks.push({ position: pxPos, height: 10, label: i / 10 > 0 ? String(i / 10) : undefined });
      } else if (i % 5 === 0) {
        ticks.push({ position: pxPos, height: 6 });
      } else {
        ticks.push({ position: pxPos, height: 3 });
      }
    }
  }

  return ticks;
}

export function positionToMargin(
  positionPx: number,
  side: 'left' | 'right',
  pageWidthPx: number,
  zoom: number
): number {
  const positionTwips = pixelsToTwips(positionPx / zoom);
  if (side === 'left') return Math.max(0, positionTwips);
  return Math.max(0, pixelsToTwips(pageWidthPx / zoom) - positionTwips);
}

export function getRulerDimensions(
  sectionProps?: SectionProperties | null,
  zoom: number = 1
): { width: number; leftMargin: number; rightMargin: number; contentWidth: number } {
  const pw = sectionProps?.pageWidth ?? DEFAULT_PAGE_WIDTH_TWIPS;
  const lm = sectionProps?.marginLeft ?? DEFAULT_MARGIN_TWIPS;
  const rm = sectionProps?.marginRight ?? DEFAULT_MARGIN_TWIPS;
  const width = twipsToPixels(pw) * zoom;
  const leftMargin = twipsToPixels(lm) * zoom;
  const rightMargin = twipsToPixels(rm) * zoom;
  return { width, leftMargin, rightMargin, contentWidth: width - leftMargin - rightMargin };
}

export function getMarginInUnits(marginTwips: number, unit: 'inch' | 'cm'): string {
  return unit === 'inch'
    ? (marginTwips / TWIPS_PER_INCH).toFixed(2) + '"'
    : (marginTwips / TWIPS_PER_CM).toFixed(1) + ' cm';
}

export function parseMarginFromUnits(value: string, unit: 'inch' | 'cm'): number | null {
  const num = parseFloat(value.replace(/[^\d.]/g, ''));
  if (isNaN(num)) return null;
  return Math.round(num * (unit === 'inch' ? TWIPS_PER_INCH : TWIPS_PER_CM));
}

export default HorizontalRuler;
